plots:
  - Epoch Accuracy:
      x: step
      y:
        results/plots/metrics/train/epoch/acc.tsv: train/epoch/acc
        results/plots/metrics/val/epoch/acc.tsv: val/epoch/acc
      y_label: accuracy
      template: smooth
  - results/plots/metrics/train/step/acc.tsv:
      template: smooth
      x: step
      y: train/step/acc
      title: Batch train accuracy per 50 steps
  - results/plots/metrics/val/step/acc.tsv:
      template: smooth
      x: step
      y: val/step/acc
      title: Val step accuracy
stages:
  download:
    cmd:
    - curl -O http://www.manythings.org/anki/fra-eng.zip
    - unzip fra-eng.zip
    - rm _about.txt fra-eng.zip
    deps:
    - http://www.manythings.org/anki/fra-eng.zip
    outs:
    - fra.txt
  train:
    cmd: python train.py
    deps:
    - fra.txt
    - train.py
    params:
    - params.py:
    outs:
    - model/model.ckpt:
        persist: true
        checkpoint: true
    - results/plots:
        cache: false
        persist: true
    metrics:
    - results/metrics.json:
        cache: false
        persist: true
