stages:
  download:
    cmd:
    - curl -O http://www.manythings.org/anki/fra-eng.zip
    - unzip fra-eng.zip
    - rm _about.txt fra-eng.zip
    deps:
    - http://www.manythings.org/anki/fra-eng.zip
    outs:
    - fra.txt
  train:
    cmd: python train.py
    deps:
    - fra.txt
    - train.py
    params:
    - params.yaml:
    outs:
    - model/model.ckpt:
        persist: true
    - results/metrics.json:
        cache: false
        persist: true
    - results/plots:
        cache: false
        persist: true
plots:
- Accuracy:
    x: step
    y:
      results/plots/metrics/train/epoch/acc.tsv: acc
      results/plots/metrics/val/acc.tsv: acc
    y_label: Accuracy
- Loss:
    x: step
    y:
      results/plots/metrics/train/epoch/loss.tsv: loss
      results/plots/metrics/val/loss.tsv: loss
    y_label: Loss
