stages:
  download:
    cmd:
    - curl -O http://www.manythings.org/anki/fra-eng.zip
    - unzip fra-eng.zip
    - rm _about.txt fra-eng.zip
    deps:
    - http://www.manythings.org/anki/fra-eng.zip
    outs:
    - fra.txt
  train:
    cmd: python train.py
    deps:
    - fra.txt
    - train.py
    params:
    - params.py:
    outs:
    - model/model.ckpt:
        persist: true
        checkpoint: true
    - predictions
    metrics:
    - results/metrics.json:
        cache: false
        persist: true
    plots:
    - results/plots:
        cache: false
        persist: true
